#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Compass.FilePicker.Resource", IsApplication=false)]

namespace Compass.FilePicker
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040009
			public static int bright_blue = 2130968585;
			
			// aapt resource value: 0x7f040005
			public static int custom_black = 2130968581;
			
			// aapt resource value: 0x7f040006
			public static int dark_red = 2130968582;
			
			// aapt resource value: 0x7f040007
			public static int dark_red_pressed = 2130968583;
			
			// aapt resource value: 0x7f040004
			public static int lightgraybackground = 2130968580;
			
			// aapt resource value: 0x7f04000a
			public static int selection_background_color = 2130968586;
			
			// aapt resource value: 0x7f040001
			public static int solid_blue = 2130968577;
			
			// aapt resource value: 0x7f040002
			public static int solid_green = 2130968578;
			
			// aapt resource value: 0x7f040000
			public static int solid_red = 2130968576;
			
			// aapt resource value: 0x7f040003
			public static int solid_yellow = 2130968579;
			
			// aapt resource value: 0x7f040008
			public static int whitesmoke = 2130968584;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020006
			public static int blue = 2130837510;
			
			// aapt resource value: 0x7f020000
			public static int borderless_button = 2130837504;
			
			// aapt resource value: 0x7f020001
			public static int filepicker_file = 2130837505;
			
			// aapt resource value: 0x7f020002
			public static int filepicker_folder = 2130837506;
			
			// aapt resource value: 0x7f020003
			public static int filepicker_new_folder = 2130837507;
			
			// aapt resource value: 0x7f020004
			public static int filepicker_previous = 2130837508;
			
			// aapt resource value: 0x7f020007
			public static int green = 2130837511;
			
			// aapt resource value: 0x7f020005
			public static int red = 2130837509;
			
			// aapt resource value: 0x7f02000a
			public static int screen_background_black = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public static int translucent_background = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public static int transparent_background = 2130837516;
			
			// aapt resource value: 0x7f020009
			public static int white = 2130837513;
			
			// aapt resource value: 0x7f020008
			public static int yellow = 2130837512;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070003
			public static int btnCancel = 2131165187;
			
			// aapt resource value: 0x7f070004
			public static int btnConfirm = 2131165188;
			
			// aapt resource value: 0x7f070009
			public static int btnCreateFolder2 = 2131165193;
			
			// aapt resource value: 0x7f070006
			public static int btnNavUp = 2131165190;
			
			// aapt resource value: 0x7f070005
			public static int directoryInfo = 2131165189;
			
			// aapt resource value: 0x7f07000b
			public static int directoryList = 2131165195;
			
			// aapt resource value: 0x7f07000a
			public static int divider = 2131165194;
			
			// aapt resource value: 0x7f07000c
			public static int file_picker_image = 2131165196;
			
			// aapt resource value: 0x7f07000d
			public static int file_picker_text = 2131165197;
			
			// aapt resource value: 0x7f07000e
			public static int filepicker_main = 2131165198;
			
			// aapt resource value: 0x7f07000f
			public static int filepicker_new_folder_item = 2131165199;
			
			// aapt resource value: 0x7f070000
			public static int folderName = 2131165184;
			
			// aapt resource value: 0x7f070001
			public static int footer = 2131165185;
			
			// aapt resource value: 0x7f070002
			public static int horizontalDivider = 2131165186;
			
			// aapt resource value: 0x7f070008
			public static int txtvSelectedFolder = 2131165192;
			
			// aapt resource value: 0x7f070007
			public static int txtvSelectedFolderLabel = 2131165191;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public static int filepicker_createfolder = 2130903040;
			
			// aapt resource value: 0x7f030001
			public static int filepicker_fragment = 2130903041;
			
			// aapt resource value: 0x7f030002
			public static int filepicker_listitem = 2130903042;
			
			// aapt resource value: 0x7f030003
			public static int filepicker_mainactivity = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public static int filepicker_menu = 2131099648;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public static int filepicker_ApplicationName = 2131034112;
			
			// aapt resource value: 0x7f050002
			public static int filepicker_cancel_label = 2131034114;
			
			// aapt resource value: 0x7f050003
			public static int filepicker_confirm_label = 2131034115;
			
			// aapt resource value: 0x7f05000c
			public static int filepicker_create_folder_error = 2131034124;
			
			// aapt resource value: 0x7f05000b
			public static int filepicker_create_folder_error_already_exists = 2131034123;
			
			// aapt resource value: 0x7f05000a
			public static int filepicker_create_folder_error_no_write_access = 2131034122;
			
			// aapt resource value: 0x7f050006
			public static int filepicker_create_folder_label = 2131034118;
			
			// aapt resource value: 0x7f050008
			public static int filepicker_create_folder_msg = 2131034120;
			
			// aapt resource value: 0x7f050009
			public static int filepicker_create_folder_success = 2131034121;
			
			// aapt resource value: 0x7f050007
			public static int filepicker_enter_folder_msg = 2131034119;
			
			// aapt resource value: 0x7f050001
			public static int filepicker_ok = 2131034113;
			
			// aapt resource value: 0x7f050005
			public static int filepicker_selected_file_label = 2131034117;
			
			// aapt resource value: 0x7f050004
			public static int filepicker_selected_folder_label = 2131034116;
			
			// aapt resource value: 0x7f05000d
			public static int filepicker_up_label = 2131034125;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
