#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SampleApplication.Resource", IsApplication=true)]

namespace SampleApplication
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Compass.FilePicker.Resource.Color.bright_blue = global::SampleApplication.Resource.Color.bright_blue;
			global::Compass.FilePicker.Resource.Color.custom_black = global::SampleApplication.Resource.Color.custom_black;
			global::Compass.FilePicker.Resource.Color.dark_red = global::SampleApplication.Resource.Color.dark_red;
			global::Compass.FilePicker.Resource.Color.dark_red_pressed = global::SampleApplication.Resource.Color.dark_red_pressed;
			global::Compass.FilePicker.Resource.Color.lightgraybackground = global::SampleApplication.Resource.Color.lightgraybackground;
			global::Compass.FilePicker.Resource.Color.selection_background_color = global::SampleApplication.Resource.Color.selection_background_color;
			global::Compass.FilePicker.Resource.Color.solid_blue = global::SampleApplication.Resource.Color.solid_blue;
			global::Compass.FilePicker.Resource.Color.solid_green = global::SampleApplication.Resource.Color.solid_green;
			global::Compass.FilePicker.Resource.Color.solid_red = global::SampleApplication.Resource.Color.solid_red;
			global::Compass.FilePicker.Resource.Color.solid_yellow = global::SampleApplication.Resource.Color.solid_yellow;
			global::Compass.FilePicker.Resource.Color.whitesmoke = global::SampleApplication.Resource.Color.whitesmoke;
			global::Compass.FilePicker.Resource.Drawable.blue = global::SampleApplication.Resource.Drawable.blue;
			global::Compass.FilePicker.Resource.Drawable.borderless_button = global::SampleApplication.Resource.Drawable.borderless_button;
			global::Compass.FilePicker.Resource.Drawable.filepicker_file = global::SampleApplication.Resource.Drawable.filepicker_file;
			global::Compass.FilePicker.Resource.Drawable.filepicker_folder = global::SampleApplication.Resource.Drawable.filepicker_folder;
			global::Compass.FilePicker.Resource.Drawable.filepicker_new_folder = global::SampleApplication.Resource.Drawable.filepicker_new_folder;
			global::Compass.FilePicker.Resource.Drawable.filepicker_previous = global::SampleApplication.Resource.Drawable.filepicker_previous;
			global::Compass.FilePicker.Resource.Drawable.green = global::SampleApplication.Resource.Drawable.green;
			global::Compass.FilePicker.Resource.Drawable.red = global::SampleApplication.Resource.Drawable.red;
			global::Compass.FilePicker.Resource.Drawable.screen_background_black = global::SampleApplication.Resource.Drawable.screen_background_black;
			global::Compass.FilePicker.Resource.Drawable.translucent_background = global::SampleApplication.Resource.Drawable.translucent_background;
			global::Compass.FilePicker.Resource.Drawable.transparent_background = global::SampleApplication.Resource.Drawable.transparent_background;
			global::Compass.FilePicker.Resource.Drawable.white = global::SampleApplication.Resource.Drawable.white;
			global::Compass.FilePicker.Resource.Drawable.yellow = global::SampleApplication.Resource.Drawable.yellow;
			global::Compass.FilePicker.Resource.Id.btnCancel = global::SampleApplication.Resource.Id.btnCancel;
			global::Compass.FilePicker.Resource.Id.btnConfirm = global::SampleApplication.Resource.Id.btnConfirm;
			global::Compass.FilePicker.Resource.Id.btnCreateFolder2 = global::SampleApplication.Resource.Id.btnCreateFolder2;
			global::Compass.FilePicker.Resource.Id.btnNavUp = global::SampleApplication.Resource.Id.btnNavUp;
			global::Compass.FilePicker.Resource.Id.directoryInfo = global::SampleApplication.Resource.Id.directoryInfo;
			global::Compass.FilePicker.Resource.Id.directoryList = global::SampleApplication.Resource.Id.directoryList;
			global::Compass.FilePicker.Resource.Id.divider = global::SampleApplication.Resource.Id.divider;
			global::Compass.FilePicker.Resource.Id.file_picker_image = global::SampleApplication.Resource.Id.file_picker_image;
			global::Compass.FilePicker.Resource.Id.file_picker_text = global::SampleApplication.Resource.Id.file_picker_text;
			global::Compass.FilePicker.Resource.Id.filepicker_main = global::SampleApplication.Resource.Id.filepicker_main;
			global::Compass.FilePicker.Resource.Id.filepicker_new_folder_item = global::SampleApplication.Resource.Id.filepicker_new_folder_item;
			global::Compass.FilePicker.Resource.Id.folderName = global::SampleApplication.Resource.Id.folderName;
			global::Compass.FilePicker.Resource.Id.footer = global::SampleApplication.Resource.Id.footer;
			global::Compass.FilePicker.Resource.Id.horizontalDivider = global::SampleApplication.Resource.Id.horizontalDivider;
			global::Compass.FilePicker.Resource.Id.txtvSelectedFolder = global::SampleApplication.Resource.Id.txtvSelectedFolder;
			global::Compass.FilePicker.Resource.Id.txtvSelectedFolderLabel = global::SampleApplication.Resource.Id.txtvSelectedFolderLabel;
			global::Compass.FilePicker.Resource.Layout.filepicker_createfolder = global::SampleApplication.Resource.Layout.filepicker_createfolder;
			global::Compass.FilePicker.Resource.Layout.filepicker_fragment = global::SampleApplication.Resource.Layout.filepicker_fragment;
			global::Compass.FilePicker.Resource.Layout.filepicker_listitem = global::SampleApplication.Resource.Layout.filepicker_listitem;
			global::Compass.FilePicker.Resource.Layout.filepicker_mainactivity = global::SampleApplication.Resource.Layout.filepicker_mainactivity;
			global::Compass.FilePicker.Resource.Menu.filepicker_menu = global::SampleApplication.Resource.Menu.filepicker_menu;
			global::Compass.FilePicker.Resource.String.filepicker_ApplicationName = global::SampleApplication.Resource.String.filepicker_ApplicationName;
			global::Compass.FilePicker.Resource.String.filepicker_cancel_label = global::SampleApplication.Resource.String.filepicker_cancel_label;
			global::Compass.FilePicker.Resource.String.filepicker_confirm_label = global::SampleApplication.Resource.String.filepicker_confirm_label;
			global::Compass.FilePicker.Resource.String.filepicker_create_folder_error = global::SampleApplication.Resource.String.filepicker_create_folder_error;
			global::Compass.FilePicker.Resource.String.filepicker_create_folder_error_already_exists = global::SampleApplication.Resource.String.filepicker_create_folder_error_already_exists;
			global::Compass.FilePicker.Resource.String.filepicker_create_folder_error_no_write_access = global::SampleApplication.Resource.String.filepicker_create_folder_error_no_write_access;
			global::Compass.FilePicker.Resource.String.filepicker_create_folder_label = global::SampleApplication.Resource.String.filepicker_create_folder_label;
			global::Compass.FilePicker.Resource.String.filepicker_create_folder_msg = global::SampleApplication.Resource.String.filepicker_create_folder_msg;
			global::Compass.FilePicker.Resource.String.filepicker_create_folder_success = global::SampleApplication.Resource.String.filepicker_create_folder_success;
			global::Compass.FilePicker.Resource.String.filepicker_enter_folder_msg = global::SampleApplication.Resource.String.filepicker_enter_folder_msg;
			global::Compass.FilePicker.Resource.String.filepicker_ok = global::SampleApplication.Resource.String.filepicker_ok;
			global::Compass.FilePicker.Resource.String.filepicker_selected_file_label = global::SampleApplication.Resource.String.filepicker_selected_file_label;
			global::Compass.FilePicker.Resource.String.filepicker_selected_folder_label = global::SampleApplication.Resource.String.filepicker_selected_folder_label;
			global::Compass.FilePicker.Resource.String.filepicker_up_label = global::SampleApplication.Resource.String.filepicker_up_label;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040009
			public const int bright_blue = 2130968585;
			
			// aapt resource value: 0x7f040005
			public const int custom_black = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int dark_red = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int dark_red_pressed = 2130968583;
			
			// aapt resource value: 0x7f040004
			public const int lightgraybackground = 2130968580;
			
			// aapt resource value: 0x7f04000a
			public const int selection_background_color = 2130968586;
			
			// aapt resource value: 0x7f040001
			public const int solid_blue = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int solid_green = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int solid_red = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int solid_yellow = 2130968579;
			
			// aapt resource value: 0x7f040008
			public const int whitesmoke = 2130968584;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020008
			public const int blue = 2130837512;
			
			// aapt resource value: 0x7f020000
			public const int borderless_button = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int filepicker_file = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int filepicker_folder = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int filepicker_new_folder = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int filepicker_previous = 2130837508;
			
			// aapt resource value: 0x7f020009
			public const int green = 2130837513;
			
			// aapt resource value: 0x7f020005
			public const int Icon = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int monoandroidsplash = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int red = 2130837511;
			
			// aapt resource value: 0x7f02000c
			public const int screen_background_black = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int translucent_background = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int transparent_background = 2130837518;
			
			// aapt resource value: 0x7f02000b
			public const int white = 2130837515;
			
			// aapt resource value: 0x7f02000a
			public const int yellow = 2130837514;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080003
			public const int btnCancel = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int btnConfirm = 2131230724;
			
			// aapt resource value: 0x7f080009
			public const int btnCreateFolder2 = 2131230729;
			
			// aapt resource value: 0x7f080011
			public const int btnDirectoryActivity = 2131230737;
			
			// aapt resource value: 0x7f080013
			public const int btnDirectoryDialog = 2131230739;
			
			// aapt resource value: 0x7f080012
			public const int btnFileActivity = 2131230738;
			
			// aapt resource value: 0x7f080014
			public const int btnFileDialog = 2131230740;
			
			// aapt resource value: 0x7f080006
			public const int btnNavUp = 2131230726;
			
			// aapt resource value: 0x7f080005
			public const int directoryInfo = 2131230725;
			
			// aapt resource value: 0x7f08000b
			public const int directoryList = 2131230731;
			
			// aapt resource value: 0x7f08000a
			public const int divider = 2131230730;
			
			// aapt resource value: 0x7f08000c
			public const int file_picker_image = 2131230732;
			
			// aapt resource value: 0x7f08000d
			public const int file_picker_text = 2131230733;
			
			// aapt resource value: 0x7f08000e
			public const int filepicker_main = 2131230734;
			
			// aapt resource value: 0x7f080016
			public const int filepicker_new_folder_item = 2131230742;
			
			// aapt resource value: 0x7f080000
			public const int folderName = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int footer = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int horizontalDivider = 2131230722;
			
			// aapt resource value: 0x7f080015
			public const int new_folder_item = 2131230741;
			
			// aapt resource value: 0x7f080010
			public const int textSelectedDirectory = 2131230736;
			
			// aapt resource value: 0x7f08000f
			public const int textView1 = 2131230735;
			
			// aapt resource value: 0x7f080008
			public const int txtvSelectedFolder = 2131230728;
			
			// aapt resource value: 0x7f080007
			public const int txtvSelectedFolderLabel = 2131230727;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int filepicker_createfolder = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int filepicker_fragment = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int filepicker_listitem = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int filepicker_mainactivity = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int directory_chooser = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int filepicker_menu = 2131165185;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050012
			public const int ApplicationName = 2131034130;
			
			// aapt resource value: 0x7f05000e
			public const int choose_directory_activity = 2131034126;
			
			// aapt resource value: 0x7f050010
			public const int choose_directory_dialog = 2131034128;
			
			// aapt resource value: 0x7f05000f
			public const int choose_file_activity = 2131034127;
			
			// aapt resource value: 0x7f050011
			public const int choose_file_dialog = 2131034129;
			
			// aapt resource value: 0x7f050000
			public const int filepicker_ApplicationName = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int filepicker_cancel_label = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int filepicker_confirm_label = 2131034115;
			
			// aapt resource value: 0x7f05000c
			public const int filepicker_create_folder_error = 2131034124;
			
			// aapt resource value: 0x7f05000b
			public const int filepicker_create_folder_error_already_exists = 2131034123;
			
			// aapt resource value: 0x7f05000a
			public const int filepicker_create_folder_error_no_write_access = 2131034122;
			
			// aapt resource value: 0x7f050006
			public const int filepicker_create_folder_label = 2131034118;
			
			// aapt resource value: 0x7f050008
			public const int filepicker_create_folder_msg = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int filepicker_create_folder_success = 2131034121;
			
			// aapt resource value: 0x7f050007
			public const int filepicker_enter_folder_msg = 2131034119;
			
			// aapt resource value: 0x7f050001
			public const int filepicker_ok = 2131034113;
			
			// aapt resource value: 0x7f050005
			public const int filepicker_selected_file_label = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int filepicker_selected_folder_label = 2131034116;
			
			// aapt resource value: 0x7f05000d
			public const int filepicker_up_label = 2131034125;
			
			// aapt resource value: 0x7f050014
			public const int none = 2131034132;
			
			// aapt resource value: 0x7f050013
			public const int selected_item = 2131034131;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Mono_Android_Theme_Splash = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
